# Generated by Django 5.1.3 on 2024-11-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_szamla_szamlaszam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szamla',
            name='szamlaszam',
            field=models.CharField(default='3180718229', max_length=20, unique=True),
        ),
    ]
