# Generated by Django 5.1.1 on 2024-11-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_szamla_szamlaszam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szamla',
            name='szamlaszam',
            field=models.CharField(default='1864589297', max_length=20, unique=True),
        ),
    ]
