# Generated by Django 5.1.1 on 2024-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_szamla_letrehozas_datum_alter_szamla_szamlaszam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szamla',
            name='szamlaszam',
            field=models.CharField(default='9378974874', max_length=20, unique=True),
        ),
    ]
